name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: sentimentregistry
  RESOURCE_GROUP: sentiment-analysis-rg
  BACKEND_APP: sentiment-backend
  FRONTEND_APP: sentiment-frontend

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push backend image
      run: |
        az acr build --registry ${{ env.AZURE_CONTAINER_REGISTRY }} \
          --image sentiment-backend:${{ github.sha }} \
          --image sentiment-backend:latest \
          --file deployment/docker/Dockerfile.backend .
    
    - name: Deploy backend to Container Apps
      run: |
        az containerapp update \
          --name ${{ env.BACKEND_APP }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sentiment-backend:${{ github.sha }}

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push frontend image
      run: |
        az acr build --registry ${{ env.AZURE_CONTAINER_REGISTRY }} \
          --image sentiment-frontend:${{ github.sha }} \
          --image sentiment-frontend:latest \
          --file deployment/docker/Dockerfile.frontend .
    
    - name: Deploy frontend to Container Apps
      run: |
        az containerapp update \
          --name ${{ env.FRONTEND_APP }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/sentiment-frontend:${{ github.sha }}
